import type { Application, Company, Job, Recommendation, UserProfile } from "../types";

export const jobs: Job[] = [
  {
    id: "JOB-001",
    company: "PT Digital Indonesia",
    companyLogo: "DI",
    position: "Frontend Developer",
    location: "Jakarta, Indonesia",
    workType: "Remote",
    jobType: "Full-time",
    experience: "Mid Level",
    salaryMin: 8_000_000,
    salaryMax: 15_000_000,
    category: "Engineering",
    description: "Bangun dashboard dan sistem karier modern dengan React, TypeScript, dan design system yang rapi.",
    postedAt: "2 hari lalu",
    deadline: "2026-07-20",
    matchScore: 95,
    status: "active",
  },
  {
    id: "JOB-002",
    company: "Nusantara Cloud",
    companyLogo: "NC",
    position: "Product Designer",
    location: "Bandung, Indonesia",
    workType: "Hybrid",
    jobType: "Full-time",
    experience: "Mid Level",
    salaryMin: 9_000_000,
    salaryMax: 16_000_000,
    category: "Design",
    description: "Rancang pengalaman produk B2B yang bersih, cepat dipindai, dan siap digunakan oleh tim operasional.",
    postedAt: "5 hari lalu",
    deadline: "2026-07-12",
    matchScore: 91,
    status: "active",
  },
  {
    id: "JOB-003",
    company: "Svara Fintech",
    companyLogo: "SF",
    position: "Backend Engineer",
    location: "Surabaya, Indonesia",
    workType: "On-site",
    jobType: "Full-time",
    experience: "Senior Level",
    salaryMin: 14_000_000,
    salaryMax: 25_000_000,
    category: "Engineering",
    description: "Kembangkan API transaksi yang aman, scalable, dan siap diintegrasikan dengan partner finansial.",
    postedAt: "7 hari lalu",
    deadline: "2026-08-01",
    matchScore: 84,
    status: "active",
  },
  {
    id: "JOB-004",
    company: "Talently Asia",
    companyLogo: "TA",
    position: "UI/UX Researcher",
    location: "Remote, Indonesia",
    workType: "Remote",
    jobType: "Contract",
    experience: "Entry Level",
    salaryMin: 6_000_000,
    salaryMax: 10_000_000,
    category: "Research",
    description: "Lakukan riset kandidat dan pengguna produk untuk meningkatkan akurasi matching pekerjaan.",
    postedAt: "10 hari lalu",
    deadline: "2026-07-30",
    matchScore: 88,
    status: "active",
  },
  {
    id: "JOB-005",
    company: "Bright EduTech",
    companyLogo: "BE",
    position: "Data Analyst",
    location: "Yogyakarta, Indonesia",
    workType: "Hybrid",
    jobType: "Full-time",
    experience: "Entry Level",
    salaryMin: 7_000_000,
    salaryMax: 12_000_000,
    category: "Data",
    description: "Olah data performa pembelajaran dan bangun insight untuk keputusan produk dan operasional.",
    postedAt: "12 hari lalu",
    deadline: "2026-07-25",
    matchScore: 79,
    status: "active",
  },
  {
    id: "JOB-006",
    company: "Karya Studio",
    companyLogo: "KS",
    position: "Mobile Developer",
    location: "Denpasar, Indonesia",
    workType: "Remote",
    jobType: "Freelance",
    experience: "Mid Level",
    salaryMin: 10_000_000,
    salaryMax: 18_000_000,
    category: "Engineering",
    description: "Bangun aplikasi mobile lintas platform dengan fokus performa, aksesibilitas, dan pengalaman premium.",
    postedAt: "18 hari lalu",
    deadline: "2026-08-10",
    matchScore: 82,
    status: "active",
  },
];

export const applications: Application[] = [
  { id: "APP-001", jobId: "JOB-001", position: "Frontend Developer", company: "PT Digital Indonesia", date: "2026-06-12", status: "Interview" },
  { id: "APP-002", jobId: "JOB-002", position: "Product Designer", company: "Nusantara Cloud", date: "2026-06-10", status: "Reviewed" },
  { id: "APP-003", jobId: "JOB-005", position: "Data Analyst", company: "Bright EduTech", date: "2026-06-08", status: "Pending" },
  { id: "APP-004", jobId: "JOB-006", position: "Mobile Developer", company: "Karya Studio", date: "2026-06-01", status: "Accepted" },
];

export const companies: Company[] = [
  {
    id: "COMP-001",
    name: "PT Digital Indonesia",
    logo: "DI",
    industry: "Technology",
    location: "Jakarta, Indonesia",
    openJobs: 12,
    description: "Perusahaan produk digital yang membangun platform SaaS untuk rekrutmen, operasional, dan data intelligence.",
    rating: 4.8,
    employees: "201-500",
  },
  {
    id: "COMP-002",
    name: "Nusantara Cloud",
    logo: "NC",
    industry: "Cloud Infrastructure",
    location: "Bandung, Indonesia",
    openJobs: 8,
    description: "Cloud partner lokal untuk bisnis modern dengan fokus keamanan, developer experience, dan skalabilitas.",
    rating: 4.7,
    employees: "501-1000",
  },
  {
    id: "COMP-003",
    name: "Svara Fintech",
    logo: "SF",
    industry: "Financial Technology",
    location: "Surabaya, Indonesia",
    openJobs: 6,
    description: "Fintech yang mengembangkan payment API, risk engine, dan produk finansial untuk UMKM Indonesia.",
    rating: 4.6,
    employees: "101-200",
  },
  {
    id: "COMP-004",
    name: "Talently Asia",
    logo: "TA",
    industry: "HR Technology",
    location: "Remote, Indonesia",
    openJobs: 15,
    description: "Platform talent intelligence untuk membantu kandidat dan perusahaan menemukan kecocokan terbaik.",
    rating: 4.9,
    employees: "51-100",
  },
];

export const profile: UserProfile = {
  name: "Ananda Faris",
  email: "ananda@careermatch.id",
  role: "job_seeker",
  headline: "Frontend Developer dengan fokus React dan UI systems",
  location: "Jakarta, Indonesia",
  skills: ["React", "TypeScript", "TailwindCSS", "Product Thinking"],
  education: "S1 Informatika, Universitas Indonesia",
  experience: "3 tahun membangun aplikasi SaaS, job portal, dan dashboard operasional.",
};

export const recommendations: Recommendation[] = jobs
  .slice()
  .sort((a, b) => b.matchScore - a.matchScore)
  .map((job, index) => ({
    ranking: index + 1,
    job,
    score: job.matchScore,
    reason: "Skill, pengalaman, preferensi work type, dan rentang gaji selaras dengan profil kamu.",
  }));
